version: '3'
services:
  webdav:
    container_name: webdav
    image: "chonjay21/webdav:latest"
    ports:
      - 85:80
     # - 443:443
    environment:
      APP_USER_NAME: webdav
      APP_USER_PASSWD: webdav
      #- APP_UID=1000
      #- APP_GID=1000
      #- APP_UMASK=007                                                 #optional
      #- TZ=America/Los_Angeles                                        #optional
      #- USE_SSL=true                                                  #optional
      #- FORCE_REINIT_CONFIG=false                                     #optional
      #- SERVER_NAME=WebDav.example.org                                #optional
      DIGEST_AUTH_REALM: WebDav                                      #optional
      #- URL_PREFIX=/webdav                                            #optional
    volumes:
      - ./volume/files:/var/webdav/data
      #- /webdav/config:/webdav/config                                 #optional
      #- /webdav/server.key:/usr/local/apache2/conf/server.key:ro      #optional
      #- /webdav/server.crt:/usr/local/apache2/conf/server.crt:ro      #optional